[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = dfu
monitor_speed = 115200

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_VID=0x0483
    -D USB_MANUFACTURER="Unknown"
    -D USB_PRODUCT="BLACKPILL_F401CC"
    -D HAL_PCD_MODULE_ENABLED
    -D PIO_FRAMEWORK_ARDUINO_USB_FULLMODE

lib_deps =
    sparkfun/SparkFun LSM9DS1 IMU@^2.0.0
    askuric/Simple FOC@^2.3.5
    arduino-libraries/Madgwick@^1.2.0
